### PR TITLE
Fix finalizers implementation for Opaque subclasses

### LINKED ISSUE #54: Objects inheriting from objects that inherit from GLib.Opaque are unrefing their handle twice.
This issue has been detected in the GStreamer bindings https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp/-/issues/58

The generator is inserting finalizers without checking if the base class for this object has one already. In objects with the  following hierarchy Gst.Message -> Gst.MiniObject -> GLib.Opaque the same finalizer is inserted for both  Gst.Message and  Gst.MiniObject.

When the GC kicks in, both finalizers are called ending with a double unref.

### PR DESCRIPTION
**Pull request by ylatuya**
There was one finalizer being for level of inheritance.
For example Gst.Message -> Gst.MiniObject -> GLib.Opaque ends
with 2 finalizers being called, one calling gst_mini_object_unreg
another one calling gst_message_unref
The following implementation will only call once the unref function
for the highest class in the hierarchy

Fixes #54

### CODE REVIEW

**Comment by ylatuya** [comment]
I don't  have a the correct set-up to re-generate all  the sources. I would need someone with the latest sources of all deps to correctly regenerate the bindings.

**Comment by ylatuya** [comment]
Everything is ready from my side now and the PR is ready for review

**Comment by thiblahute** [comment]
Have you written a patch for gst-sharp already?

**Comment by ylatuya** [comment]
I am still setting up the dev env from scratch in macOS, once done I will create a patch for gstreamer-sharp and run the unit tests I have for module using it, which is what triggered the issues with the  finalizers.

**Comment by thiblahute** [comment]
Should we wait for the GSTreamer patches to be ready/tested first?

**Comment by ylatuya** [comment]
I created the following MR in gstreamer-sharp for 1.18 https://gitlab.freedesktop.org/gstreamer/gstreamer-sharp/-/merge_requests/30

File: Source/generator/OpaqueGen.cs [hunk 1]
```diff
@@ -106,7 +106,9 @@ public override void Generate (GenerationInfo gen_info)
 				}
 			}
 
-			bool finalizer_needed = false;
+			// GtkWidgetPath has both gtk_widget_path_unref and gtk_widget_path_free
+			// If this happens add only one and prefer unref over free
+			bool disposeUnmanagedFuncAdded = false;
```
Comment (sdroege) [inline Source/generator/OpaqueGen.cs:111]: Also various types in GLib have both an unref and free function FWIW

**Review by sdroege — APPROVED** [review]
